### ISSUE TITLE
Still = at the end of long lines?

### ISSUE THREAD

**Issue by jbreitbart** [alexcesaro/quotedprintable#3]
I am not sure if this is really a bug or I am just using the decoder wrong.

Here is what I am doing:

```
dec := new(quotedprintable.WordDecoder)
b, err := dec.DecodeHeader(string(s))
```

There is no error returned, but the value returned be DecodeHeader is identical to the input. The input was:

```
http://www.ndr.de/fernsehen/sendungen/extra_3/Ein-Lied-fuer-Jean-Claude-Junc= 
ker,extra8486.html 


-- 
Sent from my mobile.= 
```

Any pointer would be highly appreciated. 

In case it is important the complete code I am running is here: https://github.com/koffeinsource/kaffeeshare/blob/master/targets/email/extractBody.go#L109

**Comment by alexcesaro** [comment]
`DecodeHeader` is meant to be used on email header like `Subject`. To decode an email body, use Reader:

```
r := quotedprintable.NewReader(strings.NewReader(s))
b, err := ioutil.ReadAll(r)
```
